#!/usr/bin/env python3
"""
audit_10usd_hit_rate.py - High-Precision $10 Profit MFE Trajectory Audit (Excluding FOMC)

Analyzes all trades generated by STRAT-XAU-001 today (July 29, 2026):
- Excludes FOMC news window (18:00 - 20:00 UTC).
- Replays price trajectory (M1 candles) between entry and exit.
- Measures how many trades reached >= $1.00/oz (+ $10.00 profit) BEFORE hitting initial SL (- $2.00) or TP (+ $5.00).
"""

import sys
import os
sys.path.insert(0, os.path.abspath("."))
import pandas as pd
from datetime import datetime, timezone, timedelta
import MetaTrader5 as mt5

def audit_10usd_hit_rate():
    print("==========================================================================================")
    print("  HIGH-PRECISION AUDIT: TRADES REACHING >= $10 PROFIT (+$1.00/oz MFE) TODAY")
    print("  (Excluding FOMC News Window 18:00 - 20:00 UTC)")
    print("==========================================================================================")

    if not mt5.initialize():
        print("[ERROR] MetaTrader 5 terminal not connected.")
        return

    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    deals = mt5.history_deals_get(today_start, datetime.now(timezone.utc) + timedelta(days=1)) or []

    bot_deals = [d._asdict() for d in deals if (d.magic == 1001 or "CAND-LIVE" in str(d.comment)) and d.entry == 0]

    # Exclude FOMC hours (18:00 - 20:00 UTC)
    filtered_deals = []
    for d in bot_deals:
        time_sec = d.get("time", 0)
        time_dt = datetime.fromtimestamp(time_sec, tz=timezone.utc)
        if 18 <= time_dt.hour < 20:
            continue
        filtered_deals.append(d)

    print(f"[DATA] Retrived {len(filtered_deals)} entry signals outside FOMC window today.\n")

    if not filtered_deals:
        print("[INFO] No trade signals found outside FOMC window.")
        return

    hit_10_count = 0
    missed_10_count = 0

    hit_10_trades = []
    missed_10_trades = []

    for deal in sorted(filtered_deals, key=lambda x: x["time"]):
        pos_id = deal.get("position_id", deal.get("order"))
        entry_p = deal.get("price", 0.0)
        entry_t_sec = deal.get("time", 0)
        direction = "BUY" if deal.get("type") == 0 else "SELL"
        symbol = deal.get("symbol", "XAUUSDz")

        init_sl = round(entry_p - 2.00, 2) if direction == "BUY" else round(entry_p + 2.00, 2)
        init_tp = round(entry_p + 5.00, 2) if direction == "BUY" else round(entry_p - 5.00, 2)

        rates = mt5.copy_rates_range(symbol, mt5.TIMEFRAME_M1, entry_t_sec, entry_t_sec + 7200)

        mfe_pts = 0.0
        hit_10 = False
        hit_sl_first = False

        if rates is not None and len(rates) > 0:
            df = pd.DataFrame(rates)
            for r in rates:
                high = r["high"]
                low = r["low"]

                if direction == "BUY":
                    if low <= init_sl:
                        hit_sl_first = True
                        break
                    if high >= (entry_p + 1.00):
                        hit_10 = True
                        mfe_pts = round(high - entry_p, 2)
                        break
                elif direction == "SELL":
                    if high >= init_sl:
                        hit_sl_first = True
                        break
                    if low <= (entry_p - 1.00):
                        hit_10 = True
                        mfe_pts = round(entry_p - low, 2)
                        break
        else:
            hit_10 = False

        trade_info = {
            "ticket": pos_id,
            "direction": direction,
            "entry_p": entry_p,
            "entry_time": datetime.fromtimestamp(entry_t_sec, tz=timezone.utc).strftime("%H:%M:%S"),
            "mfe_pts": mfe_pts,
            "hit_10": hit_10
        }

        if hit_10:
            hit_10_count += 1
            hit_10_trades.append(trade_info)
        else:
            missed_10_count += 1
            missed_10_trades.append(trade_info)

    total_analyzed = len(filtered_deals)
    pct_hit_10 = (hit_10_count / total_analyzed) * 100.0 if total_analyzed > 0 else 0.0

    print("==========================================================================================")
    print("  EXACT $10 PROFIT MFE AUDIT RESULTS SUMMARY (EXCLUDING FOMC)")
    print("==========================================================================================")
    print(f"Total Signals Analyzed Today (Excluding FOMC 18:00-20:00 UTC): {total_analyzed}")
    print(f"Trades Reaching >= $10.00 Profit (+$1.00/oz MFE) Before Initial SL: {hit_10_count} ({pct_hit_10:.1f}%)")
    print(f"Trades Failing to Reach $10.00 Profit (< +$1.00/oz MFE) / Hit SL First: {missed_10_count} ({100.0 - pct_hit_10:.1f}%)")
    print("==========================================================================================")

if __name__ == "__main__":
    audit_10usd_hit_rate()
