"""
Backtesting Core Types, Dataclasses, and Enums.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class ExitReason(Enum):
    SL_HIT = "SL_HIT"
    TP1_HIT = "TP1_HIT"
    TP2_HIT = "TP2_HIT"
    BREAKEVEN_HIT = "BREAKEVEN_HIT"
    MANUAL_CLOSE = "MANUAL_CLOSE"


@dataclass
class TradeSignal:
    """Pure signal generated by a strategy without execution assumptions."""
    timestamp: datetime
    strategy_id: str
    signal_type: SignalType
    sl_price: float
    tp1_price: float
    tp2_price: float
    order_type: OrderType = OrderType.MARKET
    limit_price: float = 0.0
    entry_target: float = 0.0
    tp1_ratio: float = 0.50
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """Tracks active position state and lifecycle."""
    position_id: str
    strategy_id: str
    signal_type: SignalType
    entry_time: datetime
    entry_price: float  # Actual filled Bid/Ask price
    original_lots: float
    current_lots: float
    sl_price: float
    tp1_price: float
    tp2_price: float
    tp1_ratio: float = 0.50
    tp1_hit: bool = False
    breakeven_locked: bool = False
    initial_risk_amount: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TradeRecord:
    """Records a completed partial or full trade execution."""
    position_id: str
    strategy_id: str
    signal_type: SignalType
    entry_time: datetime
    exit_time: datetime
    entry_price: float
    exit_price: float
    lots: float
    gross_pnl: float
    net_pnl: float
    spread_cost: float
    slippage_cost: float
    commission: float
    exit_reason: ExitReason
    session_name: str = "UNKNOWN"
    tick_validated: bool = True


@dataclass
class BacktestConfig:
    """Configuration for backtesting simulation."""
    initial_balance: float = 10000.0
    risk_pct: float = 1.0  # 1.0% equity risk per trade
    max_spread_points: int = 30  # 30 points max allowable spread ($0.30)
    slippage_pips: float = 0.2  # $0.02 slippage penalty per order
    commission_per_lot: float = 7.0  # $7.00 round-turn commission per lot
    point_value: float = 0.01  # Gold point value = $0.01
    contract_size: float = 100.0  # 1 standard lot = 100 oz of Gold
    lot_step: float = 0.01
    min_lot: float = 0.01
    max_lot: float = 50.0
    use_tick_fallback: bool = True
